"""Check for model updates

Revision ID: c18cf6fcd4ad
Revises: f391b4e7a163
Create Date: 2025-12-03 12:38:43.928831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18cf6fcd4ad'
down_revision: Union[str, None] = 'f391b4e7a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
